server {
    listen 80;
    server_name wakdo-front.acadenice.fr;

    root /app/Front;
    index accueil.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /images/ {
        root /app/Front;
        try_files $uri =404;
    }
}

server {
    listen 80;
    server_name wakdo-back.acadenice.fr;

    root /app/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location /api {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
